# Site settings
title: Friendlee
url: https://github.com/deimie/binaryBeasts-frontend
description: "A site for finding friends."
keywords: "friends, lonely, binarybeasts"
meta_author: Binary Beasts

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFB0B0 #80B3FF
  primary-rgb: "255, 176, 176" #"128,179,255"
  secondary: FF8086 #FD6E8A
  secondary-dark: FF5757 #A2122F

# Footer settings
footer:
  copyright: Binary Beasts
  location: Nighthawk Lane, San Diego, CA 92127
  social: Our Links
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nighthawkcoding
  - title: github
    url: https://github.com/deimie/binaryBeasts-frontend

# Credits content
credits: 'This page was made by the Binary Beasts CSA team.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
